language: node_js
node_js:
- 10
before_deploy:
- npm install -g rollup
- npm run build
- cd dist
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  skip_cleanup: true
  on:
    branch: master
    # tags: true
    repo: BenBrewerBowman/react-lazy-mount